name: DevHub Bot

on:
  pull_request:
    types: [opened, synchronize, closed]
  issues:
    types: [opened]

jobs:
  devhub-bot:
    uses: open-devhub/devhub-bot/.github/workflows/bot.yml@main
    secrets: inherit
